### ISSUE TITLE
Missing dependency/file?

### ISSUE THREAD

**Issue by me2d13** [bkeevil/mqtt#1]
Hi Bond
Followed your readme to compile but file passwordman.pas uses StreamUtils which is not in your lazarus repo. Where can I find this file or will you add it?

Petr

**Comment by bkeevil** [comment]
I just uploaded it into my lazarus units repository.

**Comment by me2d13** [comment]
Thanks, but in this file: CryptoUtils, Crypto?

**Comment by bkeevil** [comment]
I just uploaded my cryptography package to https://github.com/bkeevil/crypto 
I also uploaded my utilities package to https://github.com/bkeevil/bkutils

Instead of copying the files from my units repository as previously suggested, please just install my crypto package and bkutils package which contains those files.  This is how I have it set up on my machine.  I plan to eliminate those dependencies in the near future.  

I'm deleting the units repository as its no longer required and updating readme.MD to reflect new installation instructions.

**Comment by me2d13** [comment]
Thanks, now I'm able to compile & install.
Seeing the source and demo app I understand the TCP communcation must be done outside mqtt client. I tried to run client demo app but got those error on compile. Any idea? Using lazarus 1.6 win32.

MQTTClient.lpr(23,1) Error: Undefined symbol: DEBUGINFO_$MQTTCLIENT
MQTTClient.lpr(23,1) Error: Undefined symbol: DEBUGSTART_$MQTTCLIENT
MQTTClient.lpr(23,1) Error: Undefined symbol: DEBUGEND_$MQTTCLIENT
MQTTClient.lpr(23,1) Error: Undefined symbol: INIT$_$MQTTCLIENT
MQTTClient.lpr(23,1) Error: Undefined symbol: FINALIZE$_$MQTTCLIENT
MQTTClient.lpr(23,1) Error: Undefined symbol: VMT_$MQTTCLIENT_$$_TMQTTCLIENT
MQTTClient.lpr(23,1) Error: Undefined symbol: MQTTCLIENT$_$TMQTTCLIENT_$__$$_DISCONNECT
MQTTClient.lpr(23,1) Error: Undefined symbol: MQTTCLIENT$_$TMQTTCLIENT_$__$$_SETCLIENTID$UTF8STRING
MQTTClient.lpr(23,1) Error: Undefined symbol: MQTTCLIENT$_$TMQTTCLIENT_$__$$_CONNECT$$BOOLEAN
MQTTClient.lpr(23,1) Error: Undefined symbol: MQTTCLIENT$_$TMQTTCLIENT_$__$$_SUBSCRIBE$TMQTTSUBSCRIPTIONLIST$$BOOLEAN
MQTTClient.lpr(23,1) Error: Undefined symbol: MQTTCLIENT$_$TMQTTCLIENT_$__$$_UNSUBSCRIBE$TMQTTSUBSCRIPTIONLIST$$BOOLEAN
MQTTClient.lpr(23,1) Error: Undefined symbol: MQTTCLIENT$_$TMQTTCLIENT_$__$$_PUBLISH$UTF8STRING$ANSISTRING$TMQTTQOSTYPE$BOOLEAN$BOOLEAN

**Comment by bkeevil** [comment]
The demo apps use the lnet components.  Do you have those installed?

**Comment by me2d13** [comment]
Yes. However I had to use trunk version from svn as the latest distributable (6.5 I think) couldn't compile because of missing sslsockets unit (AFAIR). Anyway they're installed and I have no problem to open client form in design mode - with TCP component.

**Comment by bkeevil** [comment]
Yeah I'm not sure what could be causing those error messages and I've never seen anything like those before.  I developed the code on Linux and have never tested it with Windows.  I'll try to build on Windows tomorrow and see if I get the same results.

Edit: Found it.  The main project file has to be renamed to MQTTClientApp because MQTTClient conflicts with a class name in MQTTComponents.  Save the main project file to the new name, delete the old MQTTClient app and then recompile clean.

I'll upload the changes shortly.

**Comment by bkeevil** [comment]
Try it now

**Comment by me2d13** [comment]
Now I can compile and run.
Forms in client app are not created so I had to add code like:
```
  Application.CreateForm(TConnectDlg, ConnectDlg);
  Application.CreateForm(TSubscribeForm, SubscribeForm);
  Application.CreateForm(TPublishForm, PublishForm);
```
Which helped but I'm getting another error about send buffer size. Anyway now I can investigate further.
Will let you know if (or send PR) I find something to be fixed.
Thanks for the changes.

**Comment by bkeevil** [comment]
If I remember correctly those forms are created as needed and don't need to be in the auto-create list.

Thanks for your help.

**Comment by me2d13** [comment]
They are not, I was getting sigsegv exeption when clicking on appropriate button.
Never mind, once I have it all working will send you summary of changes I had to do.
