### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by usernametaken** [bkeevil/mqtt#27]
Apologies for my possible ignorance...

After having a quick look at the code... I see many threads being created, Lists and Queues but no CriticalSections/Locking.

Are there components Thread Safe?

**Comment by bkeevil** [comment]
I used a thread as a timer because the lazarus TTimer component was pulling in a bunch of GUI units and I wanted to be able to create non-gui applications. There were other issues with TTimer but I can't remember what they were off the top of my head. All the thread does is call a routine once per second using Synchronize() to do some processing related to the aging of sessions. Since all the processing is done in the context of the main thread it should be thread safe.
